{
 "title": "FastAPI Health",
 "tags": [
  "fastapi",
  "prometheus",
  "monitoring"
 ],
 "refresh": "30s",
 "panels": [
  {
   "title": "App Reachable",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"fastapi-alive\"}"
    }
   ]
  },
  {
   "title": "App Healthy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"fastapi-health\"}"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"fastapi-health\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"fastapi-health\"}"
    }
   ]
  }
 ]
}